# Base Brewfile for all machines

# Brew Core
# ---------------------------------------------
tap "homebrew/bundle"
tap "homebrew/services"

# Software Development Tools and Languages
# ---------------------------------------------
brew "git"
brew "libyaml"
brew "node@20"
brew "postgresql@15", restart_service: true
brew "python@3.12"
brew "uv"
brew "yarn"

# Ruby dependencies
# ---------------------------------------------
brew "libtool"
brew "pkg-config"
brew "zlib"
brew "openssl@1.1"

# Supporting tools
# ---------------------------------------------
brew "automake"
brew "gnupg"
brew "openssl@3"

# Applications
# ---------------------------------------------
brew "mas"
mas "Things", id: 904280696

cask_args appdir: "/Applications", require_sha: true
cask "1password"
cask "alfred"
cask "bartender"
cask "bruno"
cask "cleanmymac"
cask "docker-desktop"
cask "drawio"
cask "google-chrome", args: { require_sha: false }
cask "iterm2"
cask "notion"
cask "postman"
cask "visual-studio-code"
cask "zoom"

if ENV["COMPANY"] != "DELUXE"
  cask "discord"
  cask "fantastical"
end

# Applications
# ---------------------------------------------
cask_args require_sha: false # Most fonts don't have a SHA defined.
cask "font-roboto-mono"
cask "font-source-code-pro"

# VS Code Extensions
# ---------------------------------------------
if ENV["COMPANY"] == "DELUXE"
  vscode "atlassian.atlascode"
end
vscode "bradlc.vscode-tailwindcss"
vscode "bruno-api-client.bruno"
vscode "dart-code.dart-code"
vscode "dart-code.flutter"
vscode "davidanson.vscode-markdownlint"
vscode "docker.docker"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "github.copilot-chat"
vscode "github.github-vscode-theme"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "janisdd.vscode-edit-csv"
vscode "mechatroner.rainbow-csv"
vscode "mikestead.dotenv"
vscode "mongodb.mongodb-vscode"
vscode "mrmlnc.vscode-csscomb"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-ossdata.vscode-pgsql"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.vscode-chat-customizations-evaluations"
vscode "ms-vscode.vscode-github-issue-notebooks"
vscode "mtxr.sqltools"
vscode "mtxr.sqltools-driver-mysql"
vscode "mtxr.sqltools-driver-pg"
vscode "oracle.oracle-java"
vscode "redhat.java"
vscode "redhat.vscode-yaml"
vscode "shopify.ruby-lsp"
vscode "stylelint.vscode-stylelint"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscode-icons-team.vscode-icons"
