# Base Brewfile for all machines

# Brew Core
# ---------------------------------------------
tap "homebrew/bundle"
tap "homebrew/services"

# Software Development Tools and Languages
# ---------------------------------------------
brew "git"
brew "libyaml"
brew "node@20"
brew "postgresql@15", restart_service: true
brew "python@3.12"
brew "yarn"

# Ruby dependencies
# ---------------------------------------------
brew "libtool"
brew "pkg-config"
brew "zlib"
brew "openssl@1.1"

# Supporting tools
# ---------------------------------------------
brew "automake"
brew "gnupg"
brew "openssl@3"

# Applications
# ---------------------------------------------
brew "mas"

cask_args appdir: "/Applications", require_sha: true
cask "alfred"
cask "bartender"
cask "cleanmymac"
cask "docker"
cask "iterm2"
cask "postman"
cask "visual-studio-code"
cask "zoom"

# Applications
# ---------------------------------------------
cask_args require_sha: false # Most fonts don't have a SHA defined.
cask "font-roboto-mono"
cask "font-source-code-pro"

# VS Code Extensions
# ---------------------------------------------
vscode "akamud.vscode-theme-onedark"
vscode "alexkrechik.cucumberautocomplete"
vscode "bradlc.vscode-tailwindcss"
vscode "dart-code.dart-code"
vscode "dart-code.flutter"
vscode "DavidAnson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "equinusocio.vsc-material-theme"
vscode "equinusocio.vsc-material-theme-icons"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "grapecity.gc-excelviewer"
vscode "janisdd.vscode-edit-csv"
vscode "mechatroner.rainbow-csv"
vscode "mikestead.dotenv"
vscode "mongodb.mongodb-vscode"
vscode "mrmlnc.vscode-csscomb"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-ossdata.vscode-postgresql"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.vscode-github-issue-notebooks"
vscode "ms-vsliveshare.vsliveshare"
vscode "pkief.material-icon-theme"
vscode "postman.postman-for-vscode"
vscode "shopify.ruby-lsp"
vscode "siarheikuchuk.gherkin-beautifier-vs-code-plugin"
vscode "stylelint.vscode-stylelint"
